### ISSUE TITLE
Support for build matrix

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#416]
Our CI should build and test the following static configurations:

|Consensus/Enclave| Real  | Virtual |
|-| ------------- | ------------- |
|Raft| ✔️  | ✔️ + HTTP for now  |
|PBFT| ✔️  | ✔️  |

**Comment by achamayou** [comment]
I don't think we can make matrix builds work for our use case.

This works:

```
- job: Build
  strategy:
    matrix:
      No_SGX_CFT:
        cmake_args: '-DTARGET=virtual -DBUILD_SMALLBANK=OFF -DCOVERAGE=ON'
        image: ccfciteam/ccf-ci-18.04-oe-0.7.0-rc1-nosgx:latest
        options: --publish-all
        pool: Ubuntu-1804-D8s_v3
        name: No_SGX_CFT
      SGX_CFT:
        cmake_args: '-DBUILD_SMALLBANK=OFF'
        image: ccfciteam/ccf-ci-18.04-oe-0.7.0-rc1-sgx:latest
        options: --publish-all --device /dev/sgx:/dev/sgx
        pool: Ubuntu-1804-DC4s
        name: SGX_CFT
      No_SGX_BFT:
        cmake_args: '-DTARGET=virtual -DPBFT=ON -DBUILD_SMALLBANK=OFF'
        image: ccfciteam/ccf-ci-18.04-oe-0.7.0-rc1-nosgx:latest
        options: --publish-all
        pool: Ubuntu-1804-D8s_v3
        name: No_SGX_BFT
      SGX_BFT:
        cmake_args: '-DPBFT=ON -DBUILD_SMALLBANK=OFF'
        image: ccfciteam/ccf-ci-18.04-oe-0.7.0-rc1-sgx:latest
        options: --publish-all --device /dev/sgx:/dev/sgx
        pool: Ubuntu-1804-DC4s
        name: SGX_BFT

  container: $[ variables['image'] ]
```

But this doesn't:

```
   container:
     image: $[ variables['image'] ]
     options: $[ variables['options'] ]
```

Variables aren't substituted, and so the pull fails.
