### ISSUE TITLE
CCF does not install on Azure VM through cloud-init.

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/CCF#4493]
I have built an Ubuntu 20.04 OS image in Azure using a DC Series SKU. I use a cloudinit file

```yml
#cloud-config
package_update: true
package_upgrade: true
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - git
  - jq

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  - whoami
  - cd /home/azureuser && git clone https://github.com/microsoft/CCF.git ccf-install
  - sudo -u azureuser /home/azureuser/ccf-install/getting_started/setup_vm/run.sh /home/azureuser/ccf-install/getting_started/setup_vm/app-run.yml
  - export CCF_VERSION=$(curl -ILs -o /dev/null -w %{url_effective} https://github.com/microsoft/CCF/releases/latest | sed 's/^.*ccf-//')
  - wget https://github.com/microsoft/CCF/releases/download/ccf-${CCF_VERSION}/ccf_${CCF_VERSION}_amd64.deb
  - apt install /home/azureuser/ccf_${CCF_VERSION}_amd64.deb -y
  - /opt/ccf/bin/cchost --version
```

When I look in the logs of cloudinit, it has failed in an error: - 

```bash
TASK [ccf_install : Copy cchost] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Source /opt/ccf_sgx/bin/cchost not found"}

PLAY RECAP *********************************************************************
localhost                  : ok=16   changed=9    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Expected behavior**
This line should install the CCF pre-requisites.
```bash
sudo -u azureuser /home/azureuser/ccf-install/getting_started/setup_vm/run.sh /home/azureuser/ccf-install/getting_started/setup_vm/app-run.yml
```

**Environment information**
Clone of the latest code base (2.0.8) SGX, DC Series

**Additional context**
This is running under the cloudinit process

**Comment by achamayou** [comment]
@ross-p-smith the issue is that this is pulling playbooks from main, but installing 2.0.8. There have been file renames to support the addition of a new architecture that mean this won't work.

If you adjust your git checkout to grab the tag that matches the release you use, this should work.

**Comment by ross-p-smith** [comment]
Perfect! Can confirm this now works. Final cloudinit setup is: - 

```yaml
#cloud-config
package_update: true
package_upgrade: true
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - git
  - jq

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  - cd /home/azureuser && git clone https://github.com/microsoft/CCF.git ccf-install -b release/2.x
  - sudo -u azureuser /home/azureuser/ccf-install/getting_started/setup_vm/run.sh /home/azureuser/ccf-install/getting_started/setup_vm/app-run.yml
  - export CCF_VERSION=$(curl -ILs -o /dev/null -w %{url_effective} https://github.com/microsoft/CCF/releases/latest | sed 's/^.*ccf-//')
  - wget https://github.com/microsoft/CCF/releases/download/ccf-${CCF_VERSION}/ccf_${CCF_VERSION}_amd64.deb
  - apt install /home/azureuser/ccf_${CCF_VERSION}_amd64.deb -y
```

Shall I add this cloudinit for your docs against this bug - would that be of use?
